config/routes.rb
Allworld::Application.routes.draw do
  post 'ajax/showhide'

  mount Ckeditor::Engine => '/ckeditor'
  get "persons/profile"
  get 'persons/profile', as: 'user_root'
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/place/:tag', to: 'home#place'
  get '/country/:tag', to: 'home#country'
  get '/allnews', to: 'home#allnews'
  post '/allnews_filter', to: 'home#allnews_filter'
  post '/allnews_showmore', to: 'home#allnews_showmore'
  post '/allnews_showmore_events', to: 'home#allnews_showmore_events'
  post '/allnews_showmore_news', to: 'home#allnews_showmore_news'
  post '/all_country_news_showmore', to: 'home#all_country_news_showmore'
  post '/next_news', to: 'home#next_news'
  post '/prev_news', to: 'home#prev_news'
  get '/news/:tag', to: 'home#news'
  get '/countries/:tag', to: 'home#countries'
  get '/section/:tag', to: 'home#section'
  get '/categories/:tag', to: 'home#categories'
  get '/allbest', to: 'home#allbest'
  get '/allwonders', to: 'home#allwonders'
  get '/allcountries', to: 'home#allcountries'
  get '/goroda', to: 'home#goroda'
  get '/search', to: 'application#search'

  get '/seen/:id', to: 'home#seen'
  get '/multyseen/:id/:country', to: 'home#multyseen'
  post '/multiseen/:id', to: 'placevidels#multiseen', as: :placevidels_multiseen
  get '/seenjs/:id', to: 'ajax#seenjs'
  get '/wishjs/:id', to: 'ajax#wishjs'
  get '/w', to: 'ajax#setsize'
  get '/wish/:id', to: 'home#wish'
  post '/multiwish/:id', to: 'placevidels#multiwish', as: :placevidels_multiwish
  get '/no/:id', to: 'home#no'

  get '/noseen/:id', to: 'home#noseen'
  get '/nowish/:id', to: 'home#nowish'
  get '/nono/:id', to: 'home#nono'

  get '/clickandgo/:id', to: 'home#clickandgo'

  get '/articles/:tag', to: 'home#submenu'
  get '/article/:tag', to: 'home#page'

  get "guide", to: 'home#index', :as =>'guide'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  
  get '/users/profile' => 'users#edit', as: :profile
  match '/users/update_profile' => 'users#update', via: [:put, :patch], as: :update_profile

  get '/api/search' => 'application#api_search', as: :api_search

  root :to => 'home#index'

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :descrip, :hint, :name, :sortorder, :googlemap
  has_one :tag, :as => :content
  has_many :countries
  has_many :showplaces
  after_create :add_tag
  
  def add_tag
    self.tag = Tag.new
    tag  = self.name.to_slug_param
    i    = 1
    ttag = tag
    while Tag.find_by_name(ttag).present? 
      ttag  = tag + '_' + i.to_s
      i = i + 1
    end
    self.tag.name = ttag
    self.tag.save
  end
  rails_admin do
    navigation_label I18n.t('menu.menu')
    list do
      sort_by :sortorder
      field :sortorder
      field :name
      field :tag
    end
    edit do
      include_all_fields
      field :descrip, :ck_editor
      field :hint, :ck_editor
    end
  end

end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
  respond_to :html, :json

  before_filter :load_showplace, only: [:wishjs, :seenjs]

  def setsize
    testperpaged = $perpaged
    if params[:w].to_i>1599
      session[:perpaged] = 5
      $perpaged = 5
    elsif params[:w].to_i>1199 and params[:w].to_i<1600
      session[:perpaged] = 4
      $perpaged = 4
    elsif params[:w].to_i>991 and params[:w].to_i<1200
      session[:perpaged] = 3
      $perpaged = 3
    elsif params[:w].to_i<992
      session[:perpaged] = 2
      $perpaged = 2
    end
    $countobj = 4*$perpaged
    render text: testperpaged.to_s
  end


  def showhide
    if params[:showed]==t('ajax.hide')
      session[:marqueshow] = false
      render text: t('ajax.show')
    else
      session[:marqueshow] = true
      render text: t('ajax.hide')
    end
  end

  def seenjs
    if @showplace.countries.count < 2
      @topage = "/seen/"+params[:id]
      redirect_to "/seen/"+params[:id]
    else
      @marked_countries = []
      if current_user
        if shplece = current_user.placevidels.find_by_showplace_id(params[:id])
          @marked_countries = shplece.countryarray.split(",").map { |s| s.to_i }
        end
      else
        unless session[:placevidelscountries].nil? 
          if session[:placevidelscountries][params[:id].to_i].kind_of?(Array)
            @marked_countries = session[:placevidelscountries][params[:id].to_i] || []
          end
        end
      end
    end
  end

  def wishjs
    if @showplace.countries.length < 2
      redirect_to "/wish/#{params[:id]}"
    else
      @marked_countries = []
      if current_user
        currently_wished = current_user.placedas.find_by_showplace_id(params[:id])
        @marked_countries = currently_wished.try(:countries) if currently_wished
      else
        @marked_countries = (session[:placedascountries][@showplace.id] || []) if session[:placedascountries] && session[:placedascountries].any?
      end
    end
  end

private

  def load_showplace
    @showplace = Showplace.find params[:id]
  end

end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/views/ajax/_addcounties.html.haml
.modal-dialog#addcountries
  .modal-content
    .well
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %h5
        Пожалуйста выберите страну, в которой Вы видели 
        = @showplace.name

      %hr
      = form_tag form_url, remote: true do
        - placevidelsclass = 'bignocheck'
        .countries
          - @showplace.countries.each do |country|
            .country_item
              = label_tag do
                = check_box_tag 'country_ids[]', country.id, @marked_countries.include?(country.id.to_i)
                .flag_img
                  - if flagimg = country.flag.url(:thumb)
                    = image_tag flagimg
                = country.name
        .text-right
          = submit_tag "OK", class: "btn btn-primary", style: "min-width:100px;margin:0 10px 10px 0;", data: { disable_with: "Загрузка..." }

app/views/ajax/redirect.js.erb
window.location.href = "<%= @topage %>";

app/views/ajax/seenjs.js.erb
$("#extend-modal").html("<%= escape_javascript(render 'addcounties', form_url: placevidels_multiseen_path) %>")
$("#extend-modal").modal("show")

app/views/ajax/wishjs.js.erb
$("#extend-modal").html("<%= escape_javascript(render 'addcounties', form_url: placevidels_multiwish_path) %>")
$("#extend-modal").modal("show")