config/routes.rb
Allworld::Application.routes.draw do
  post 'ajax/showhide'

  mount Ckeditor::Engine => '/ckeditor'
  get "persons/profile"
  get 'persons/profile', as: 'user_root'
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/place/:tag', to: 'home#place'
  get '/country/:tag', to: 'home#country'
  get '/allnews', to: 'home#allnews'
  post '/allnews_filter', to: 'home#allnews_filter'
  post '/allnews_showmore', to: 'home#allnews_showmore'
  post '/allnews_showmore_events', to: 'home#allnews_showmore_events'
  post '/allnews_showmore_news', to: 'home#allnews_showmore_news'
  post '/all_country_news_showmore', to: 'home#all_country_news_showmore'
  post '/next_news', to: 'home#next_news'
  post '/prev_news', to: 'home#prev_news'
  get '/news/:tag', to: 'home#news'
  get '/countries/:tag', to: 'home#countries'
  get '/section/:tag', to: 'home#section'
  get '/categories/:tag', to: 'home#categories'
  get '/allbest', to: 'home#allbest'
  get '/allwonders', to: 'home#allwonders'
  get '/allcountries', to: 'home#allcountries'
  get '/goroda', to: 'home#goroda'
  get '/search', to: 'application#search'

  get '/seen/:id', to: 'home#seen'
  get '/multyseen/:id/:country', to: 'home#multyseen'
  post '/multiseen/:id', to: 'placevidels#multiseen', as: :placevidels_multiseen
  get '/seenjs/:id', to: 'ajax#seenjs'
  get '/wishjs/:id', to: 'ajax#wishjs'
  get '/w', to: 'ajax#setsize'
  get '/wish/:id', to: 'home#wish'
  post '/multiwish/:id', to: 'placevidels#multiwish', as: :placevidels_multiwish
  get '/no/:id', to: 'home#no'

  get '/noseen/:id', to: 'home#noseen'
  get '/nowish/:id', to: 'home#nowish'
  get '/nono/:id', to: 'home#nono'

  get '/clickandgo/:id', to: 'home#clickandgo'

  get '/articles/:tag', to: 'home#submenu'
  get '/article/:tag', to: 'home#page'

  get "guide", to: 'home#index', :as =>'guide'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  
  get '/users/profile' => 'users#edit', as: :profile
  match '/users/update_profile' => 'users#update', via: [:put, :patch], as: :update_profile

  get '/api/search' => 'application#api_search', as: :api_search

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  has_many :placedas, :dependent => :destroy
  has_many :placenets, :dependent => :destroy
  has_many :placevidels, :dependent => :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :lastmarquee
  attr_accessible :name, :family, :role
  attr_accessible :avatar

  attr_accessible :country, :city, :gender, :birthday
  attr_accessible :facebook_link, :twitter_link, :vk_link, :instagram_link, :google_link

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :micro => "50x50#" }, :default_url => "/default_avatar.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  attr_accessor :login

  validates_uniqueness_of :username


  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      # email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email
      user = User.where(email: email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: (auth.info.nickname && auth.info.nickname.present? ? auth.info.nickname : auth.uid),
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        # user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
  # attr_accessible :title, :body
  def role_enum
    %w[admin manager member]
  end

  def role?(role)
    self.role == role.to_s
  end

  def has_extended_role?
    %w(admin manager).include? self.role
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  def wish_countries_ids
    placedas.pluck(:countries).flatten.uniq
  end

  def wish_countries
    Country.where id: wish_countries_ids
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: :finish_signup
  layout "persons", only: [:edit, :update]

	# GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        # @user.skip_reconfirmation!
        sign_in(@user, bypass: true)
        redirect_to user_root_path, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  def edit
    @user = current_user
    @errors = {}
  end

  def update
    @user = current_user

    if params[:commit] == "Изменить пароль"
      permitted_params = params.require(:user).permit!

      unless @user.valid_password? permitted_params[:current_password]
        @user.errors.add(:current_password, permitted_params[:current_password].blank? ? :blank : :invalid)
      else
        @user.update permitted_params
        sign_in(current_user, bypass: true) if @user.valid?
      end
    else
      permitted_params = params.require(:user).permit(:username, :email, :first_name, :last_name, :country, :city, :gender, :birthday, :avatar)
      @user.update permitted_params
    end

    if request.format != :js
      if @user.errors.any?
        redirect_to profile_path
      else
        render :edit
      end
    end

  end

private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation, :current_password ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end

end

app/views/users/edit.erb
<% set_meta_tags title: "Изменить информацию", reverse: true %>

<div class="container-fluid">
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1 class='textcenter'>Профиль пользователя</h1>
    </div>
  </div>
</div>

<% if !@user.valid? %>
  <div id="error_explanation" class="text-danger" style="margin-bottom:20px;">
    <%- @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
      <br>
  </div>
<% end %>


<div class="row">
  <%= form_for(@user, url: update_profile_path(), html: { method: :put, class: "form-horizontal" }) do |f| %>
    <div class="col-md-5">
      <h4 class="text-center">Аватар</h4>
      <div class="text-center" style="margin-bottom:10px;"><%= image_tag f.object.avatar.url(:medium), style: "max-width:300px;" %></div>
      <div class='field form-group'><%= f.label :avatar, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.file_field :avatar, class: "form-control" %>
        </div>
      </div>

      <h4 class="text-center">Профили в соц. сетях</h4>

      <div class='field form-group'><%= f.label :facebook_link, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :facebook_link, class: "form-control" %>
        </div>
      </div>
      <div class='field form-group'><%= f.label :twitter_link, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :twitter_link, class: "form-control" %>
        </div>
      </div>
      <div class='field form-group'><%= f.label :vk_link, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :vk_link, class: "form-control" %>
        </div>
      </div>
      <div class='field form-group'><%= f.label :instagram_link, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :instagram_link, class: "form-control" %>
        </div>
      </div>
      <div class='field form-group'><%= f.label :google_link, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :google_link, class: "form-control" %>
        </div>
      </div>

    </div>
    <div class="col-md-7">
      <h4 class="text-center">Общая информация</h4>
      <div class='field form-group'><%= f.label :username, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :username, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :email, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.email_field :email, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>


      <div class='field form-group'><%= f.label :password, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.password_field :password, class: "form-control", style: "max-width: 300px;display:inline-block;" %>
          <%= link_to "Изменить пароль", '#change_password', class: "btn btn-primary", data: { toggle: "modal", target: "#change_password" }  %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :name, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :name, autofocus: true, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :family, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :family, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :country, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :country, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :city, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :city, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :gender, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :gender, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'><%= f.label :birthday, class: "col-sm-3 control-label" %>
        <div class="col-sm-8" style="margin: 0 20px;">
          <%= f.text_field :birthday, class: "form-control", style: "max-width: 300px;" %>
        </div>
      </div>

      <div class='field form-group'>
        <div><%= f.submit "Сохранить изменения", class:'btn btn-primary btn-block', style: "max-width:300px;margin-left:210px;" %></div><br /><br /></div>
      <div class="clear"></div>
    </div>
  <% end %>

  </div>
</div>

<%= render 'shared/change_password' %>

app/views/users/finish_signup.html.haml
#add-email
  %h2 Завершение регистрации
  = form_for(current_user, as: 'user', url: finish_signup_path(current_user), html: { role: 'form'}) do |f|
    .form-group
      = f.label :email
      .controls
        = f.text_field :email, autofocus: true, value: '', class: 'form-control input-lg', placeholder: 'Например: email@me.com'
        %p.help-block Пожалуйста, укажите ваш адрес электронной почты
    - if @show_errors && @user.errors.any?
      #error_explanation.text-danger(style="margin-bottom:20px;")
        - @user.errors.full_messages.each do |msg|
          = msg
          %br
    .actions
      = f.submit 'Продолжить', class: 'btn btn-primary'

app/views/users/update.js.erb
<% if @user.errors.any? %>
	$("#change-password-body").html("<%= j render 'shared/change_password_body' %>");
<% else %>
	window.location.reload();
<% end %>