config/routes.rb
Allworld::Application.routes.draw do
  post 'ajax/showhide'

  mount Ckeditor::Engine => '/ckeditor'
  get "persons/profile"
  get 'persons/profile', as: 'user_root'
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/place/:tag', to: 'home#place'
  get '/country/:tag', to: 'home#country'
  get '/allnews', to: 'home#allnews'
  post '/allnews_filter', to: 'home#allnews_filter'
  post '/allnews_showmore', to: 'home#allnews_showmore'
  post '/allnews_showmore_events', to: 'home#allnews_showmore_events'
  post '/allnews_showmore_news', to: 'home#allnews_showmore_news'
  post '/all_country_news_showmore', to: 'home#all_country_news_showmore'
  post '/next_news', to: 'home#next_news'
  post '/prev_news', to: 'home#prev_news'
  get '/news/:tag', to: 'home#news'
  get '/countries/:tag', to: 'home#countries'
  get '/section/:tag', to: 'home#section'
  get '/categories/:tag', to: 'home#categories'
  get '/allbest', to: 'home#allbest'
  get '/allwonders', to: 'home#allwonders'
  get '/allcountries', to: 'home#allcountries'
  get '/goroda', to: 'home#goroda'
  get '/search', to: 'application#search'

  get '/seen/:id', to: 'home#seen'
  get '/multyseen/:id/:country', to: 'home#multyseen'
  post '/multiseen/:id', to: 'placevidels#multiseen', as: :placevidels_multiseen
  get '/seenjs/:id', to: 'ajax#seenjs'
  get '/wishjs/:id', to: 'ajax#wishjs'
  get '/w', to: 'ajax#setsize'
  get '/wish/:id', to: 'home#wish'
  post '/multiwish/:id', to: 'placevidels#multiwish', as: :placevidels_multiwish
  get '/no/:id', to: 'home#no'

  get '/noseen/:id', to: 'home#noseen'
  get '/nowish/:id', to: 'home#nowish'
  get '/nono/:id', to: 'home#nono'

  get '/clickandgo/:id', to: 'home#clickandgo'

  get '/articles/:tag', to: 'home#submenu'
  get '/article/:tag', to: 'home#page'

  get "guide", to: 'home#index', :as =>'guide'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  
  get '/users/profile' => 'users#edit', as: :profile
  match '/users/update_profile' => 'users#update', via: [:put, :patch], as: :update_profile

  get '/api/search' => 'application#api_search', as: :api_search

  root :to => 'home#index'

end

app/views/shared/_allnews_tabmenu.html.haml
.tabmenu-background.transparent
  .container
    .tabmenu
      .tabmenu-header
        .tab-link.active
          %span{"tab-id" => "fresh_news"}
            Новости
        .tab-link
          %span{"tab-id" => "all_news_events"}
            События

      .tab-panel.row.active{id: "fresh_news"}
        .row.no-margin.fresh-news-block
          - piece = @last_news.first
          - if piece.present?
            .col-md-6.main-news.gray-shadow{onclick: "window.location = '/news/"+piece.tag+"'"}
              .fresh-news-container
                .news-title.single-line
                  = link_to piece.name, "/news/"+piece.tag
                %span.news-date
                  = piece.posted_on.try(:strftime, ("%d.%m.%Y"))
                %p
                - if tmpimage = piece.newspictures.first
                  .showplace_wcorner_100
                    .showplace_img_50
                      = image_tag tmpimage.image.url(:medium)
                %p
                .fresh-news-text
                  = piece.page.html_safe
          .col-md-6
            - @last_news.select{|ln| ln.id != @last_news.first.id}.each do |piece|
              .older-news.gray-shadow{onclick: "window.location = '/news/"+piece.tag+"'"}
                .older-news-container
                  .inherit-height
                    .news-title.single-line
                      = link_to piece.name, "/news/"+piece.tag
                    %span.news-date
                      = piece.posted_on.try(:strftime, ("%d.%m.%Y"))

                    .tcell(style="width:43%;")
                      - if tmpimage = piece.newspictures.first
                        .showplace_wcorner_40
                          .showplace_img
                            = image_tag tmpimage.image.url(:medium)
                    .tcell
                      .older-news-text
                        = piece.page.html_safe

      .tab-panel.row{id: "all_news_events"}
        .row.no-margin.fresh-news-block
          - piece = @last_events.first
          - if piece.present?
            .col-md-6.main-news.gray-shadow{onclick: "window.location = '/news/"+piece.tag+"'"}
              .fresh-news-container
                .news-title.single-line  
                  = link_to piece.name, "/news/"+piece.tag
                %span.news-date
                  = piece.posted_on.try(:strftime, ("%d.%m.%Y"))
                %p
                - if tmpimage = piece.newspictures.first
                  .showplace_wcorner_100
                    .showplace_img_50
                      = image_tag tmpimage.image.url(:medium)
                %p
                .fresh-news-text
                  = piece.page.html_safe
          .col-md-6
            - @last_events.select{|ln| ln.id != @last_events.first.id}.each do |piece|
              .older-news.gray-shadow{onclick: "window.location = '/news/"+piece.tag+"'"}
                .older-news-container
                  .inherit-height
                    .news-title.single-line 
                      = link_to piece.name, "/news/"+piece.tag
                    %span.news-date
                      = piece.posted_on.try(:strftime, ("%d.%m.%Y"))

                    .tcell(style="width:43%;")
                      - if tmpimage = piece.newspictures.first
                        .showplace_wcorner_40
                          .showplace_img
                            = image_tag tmpimage.image.url(:medium)
                    .tcell
                      .older-news-text
                        = piece.page.html_safe


.tabmenu-background
  .container 
    .tabmenu.constant
      .tabmenu-header
        .tab-link.active
          %span{"tab-id" => "all_news"}
            Другие новости и события

      .tab-panel.row.active{id: "all_news"}
        .shpage
        .textsblocks
          = render "allnews_all_tab"

app/views/shared/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel" data-interval="7000">
  <!-- Indicators -->
<%
if block=='root' then slides=Slider.all.where(:showinroot=>true).order('sortorder ASC') end
if block=='guide' then slides=Slider.all.where(:showinguide=>true).order('sortorder ASC') end
indicators  = '<ol class="carousel-indicators">'
items       = ''
firctactive='active'
counterslide=0
slides.each do |slide|
  indicators +='<li data-target="#carousel-example-generic" data-slide-to="'+counterslide.to_s+'" class="'+firctactive+'"></li>'
  items +='<div class="item '+firctactive+'">'
  items +='<img src="'+slide.image.url(:slide)+'" alt="'+slide.name+'">'
  items +='<div class="carousel-caption_ext">'
  items +='<div class="carousel-caption">'+slide.description.html_safe+'</div>'
  items +='<div class="carousel-title">'+slide.name.html_safe+'</div>'
  items +='</div>'
  items +='</div>'
  
  firctactive   =''
  counterslide += 1
end
indicators += '</ol>'
%>
<%= indicators.html_safe %>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
<%= items.html_safe %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <!-- <span class="fa fa-chevron-left" aria-hidden="true"></span> -->
    <!-- <span class="sr-only">Previous</span> -->
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <!-- <span class="fa fa-chevron-right" aria-hidden="true"></span> -->
    <!-- <span class="sr-only">Next</span> -->
  </a>
</div>
<style>
.carousel-fade .carousel-inner .item {
  opacity: 0;
  transition-property: opacity;
}

.carousel-fade .carousel-inner .active {
  opacity: 1;
}

.carousel-fade .carousel-inner .active.left,
.carousel-fade .carousel-inner .active.right {
  left: 0;
  opacity: 0;
  z-index: 1;
}

.carousel-fade .carousel-inner .next.left,
.carousel-fade .carousel-inner .prev.right {
  opacity: 1;
}

.carousel-fade .carousel-control {
  z-index: 2;
}

/*
WHAT IS NEW IN 3.3: "Added transforms to improve carousel performance in modern browsers."
now override the 3.3 new styles for modern browsers & apply opacity
*/
@media all and (transform-3d), (-webkit-transform-3d) {
    .carousel-fade .carousel-inner > .item.next,
    .carousel-fade .carousel-inner > .item.active.right {
      opacity: 0;
      -webkit-transform: translate3d(0, 0, 0);
              transform: translate3d(0, 0, 0);
    }
    .carousel-fade .carousel-inner > .item.prev,
    .carousel-fade .carousel-inner > .item.active.left {
      opacity: 0;
      -webkit-transform: translate3d(0, 0, 0);
              transform: translate3d(0, 0, 0);
    }
    .carousel-fade .carousel-inner > .item.next.left,
    .carousel-fade .carousel-inner > .item.prev.right,
    .carousel-fade .carousel-inner > .item.active {
      opacity: 1;
      -webkit-transform: translate3d(0, 0, 0);
              transform: translate3d(0, 0, 0);
    }
}
</style>

app/views/shared/_country.html.haml
.country_wcorner
  =link_to "/country/"+country.tag do
    -if flagimg = country.flag.url(:thumb)
      =image_tag flagimg, :class => 'flag', :alt => country.name, :title => country.name
      %p=country.name

app/views/shared/_footer.html.haml
.container
  .row
    .footer-table
      .footer-cell.right-s{style: "width: 35%"}
        = raw Setting.footer_text
      / .afdelimit

      .footer-cell{style: "width: 45%"}
        - Footermenu.order('sortorder ASC').each do |razdel|
          .text-center.display-as-inline-block(style="float:left;width:50%;")
            / %h4=razdel.name
            .text-left.display-as-inline-block
              -razdel.footersubmenus.order('sortorder ASC').each do |subfooter|
                %p
                  = link_to subfooter.url do
                    - if subfooter.icon.present?
                      = image_tag subfooter.icon.url(:micro), width: "40"
                    = subfooter.name
        / .afdelimit

      .footer-cell.left-s.text-right.display-as-inline-block
        .text-left.display-as-inline-block
          %h4 Контакты
          %p
            = "e-mail: #{Setting.system_email}"
          %p
            = image_tag "support_white.png", size: "20x20"
            Служба поддержки
          -#=$setting.contactadress
          .socialicons
            = link_to Setting.vk_link, target: "_blank" do
              %span#icovk
            = link_to Setting.fb_link, target: "_blank" do
              %span#icofb
            = link_to Setting.instagram_link, target: "_blank" do
              %span#icoin
            = link_to Setting.twitter_link, target: "_blank" do
              %span#icotw
            = link_to Setting.youtube_link, target: "_blank" do
              %span#icoyb
            = link_to Setting.google_link, target: "_blank" do
              %span#icogp
      

app/views/shared/_gcs.html.erb
<script>
      (function() {
        var cx = '004728215443290035183:ubglquunv5a';
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
      })();
    </script>
    <gcse:search></gcse:search>

app/views/shared/_hiddenbottom.html.haml
- unless user_signed_in?
  .registermpdal
    = render :partial => 'shared/signup'
  .signmodal
    = render :partial => 'shared/signin'
  .savesettings
    = render :partial => 'shared/onexit'
.modal.fade#extend-modal
= render :partial => 'shared/analitics'
= render :partial => 'shared/scripts'
= javascript_include_tag "signup"

app/views/shared/_lang.html.erb
<ul class="dropdown-menu dropdown-menu-right">
<li>
<a href="/"><img style="width: 36px;height: 20px;" src="/img/ru.png" alt="Ru">
Русский
</a></li>
<li>
  <div style="padding: 3px 20px;">
<img style="width: 36px;height: 20px;" src="/img/en.png" alt="En">
English
</div>
</li>
</ul>

app/views/shared/_loginblock.html.haml
- if user_signed_in?
  %li.dropdown
    = link_to user_root_path, data: { toggle: "dropdown" }, role: "button", aria: { haspopup: true, expanded: false } do
      = image_tag current_user.avatar.url(:micro), class: "img-circle", size: "25x25"
      = current_user.login
      %span.langdown
    %ul.dropdown-menu.dropdown-menu-right
      %li= link_to "Профиль", user_root_path
      %li= link_to "Выход", destroy_user_session_path, method: :delete
  %li
    %span.delimiter 
  %li
    = link_to t('user.logoutblock'), destroy_user_session_path, :method => :delete
  %li
    %span.delimiter 

  -#.old
    %li
      = link_to edit_user_registration_path do
        %span.fa.fa-user
        %span
    - if can? :dashboard, User
      %li
        = link_to '/admin' do
          %span.fa.fa-dashboard
          %span
    %li
      = link_to user_root_path do
        %span.fa.fa-home
        %span
    %li
      = link_to destroy_user_session_path, :method => :delete do
        %span.fa.fa-sign-out
        %span
- else
  %li
    = link_to t('user.register'), "#sign_up", 'data-toggle' => "modal", 'data-target' => "#sign_up"
  %li
    %span.delimiter 
  %li
    = link_to t('user.signblock'), "#sign_in", 'data-toggle' => "modal", 'data-target' => "#sign_in"
  %li
    %span.delimiter 

app/views/shared/_loginform.html.haml
.loginform
  %ul.list-unstyled
    -#%li.nav-header Авторизация
    %br
    - if user_signed_in?
      %li
        = link_to edit_user_registration_path do
          =current_user.email
      - if can? :dashboard, User
        %li
          = link_to '/admin' do
            Панель управления
      %li
        = link_to user_root_path do
          Моя страница
      %li= link_to "Выйти", destroy_user_session_path, :method => :delete

    - else
      = form_tag session_path(:user), {:style=>'margin: 0 0 0;'} do
        = text_field_tag 'user[email]', nil, placeholder: 'E-mail', style: 'width: 90%;margin: auto;', :class => "form-control"
        = password_field_tag 'user[password]', nil, placeholder: 'Пароль', style: 'width: 90%;margin: auto;', :class => "form-control"
        %button{:class => 'btn btn-default', :style => 'width:95%;'} Войти
      = link_to t('user.register'), "#sign_up", :remote => true, 'data-toggle' => "modal", 'data-target' => "#sign_up", :method => 'get', style: 'font-size: 11px;'
      \|
      = link_to "Забыли пароль?", new_password_path(:user), style: 'font-size: 11px;'

app/views/shared/_marquee.html.haml
- if current_user
  - current_user.lastmarquee =0 if current_user.lastmarquee.blank?
  -# @marq = Marquee.where('id > ?', current_user.lastmarquee.to_i).last(10)
  - @marq = Marquee.last(10)
  - current_user.lastmarquee = Marquee.last.id
  - current_user.save
- else
  - @marq = Marquee.last(10)
- if session[:marqueshow].nil? or session[:marqueshow] 
  - showorhide = t('ajax.hide')
  - shstyle = 'display: block;'
- else
  - showorhide = t('ajax.show')
  - shstyle = 'display: none;'
- if @marq.present?
  .marqueeblocks
    - if current_user
      #hidemarqueeblock.textcenter
        %p#hidemarquee{class: showorhide}
  .marquee#marqueeblock{ style: shstyle }
    .marquee-container
      - @marq.each do |marquee|
        = marquee.full
        = image_tag '/img/mir.gif',:style=>"width:14px; height:14px;"


  / .marqueeblocks
  /   - if current_user
  /     #hidemarqueeblock.textcenter
  /       %p#hidemarquee{class: showorhide}
  / .marquee
  /   .marquee_block
  /     %marquee#marqueeblock{"direction"=>"left", "scrollamount"=>"2", "loop"=>"1", :style=>shstyle}
  /       - @marq.each do |marquee|
  /         =marquee.full
  /         =image_tag '/img/mir.gif',:style=>"width:14px; height:14px;"
  /         -# marquee.showcount = 0 if marquee.showcount.nil?
  /         -# marquee.showcount = marquee.showcount+1
  /         -# marquee.save
- else 
  .pull-left
  .marquee
    .marquee_block

app/views/shared/_nextblockshowplace.html.erb
</div>
<div class='nextsh'>
<%= link_to_next @showplaces, {:param_name => :shpage, :remote => true}, (image_tag '/img/content_arr_slider_right.png') %>
</a></div>
</div>

app/views/shared/_partners.html.haml
.textsblocks
	%b 
		%span.fa.fa-thumbs-o-up
		Авиабилеты, отели, прокат авто
	.ad-div.text-center= object.get_hotels_code.try :html_safe
	%br
	.ad-div.text-center= object.get_flights_code.try :html_safe
	%br
	.ad-div.text-center= object.get_car_rental_code.try :html_safe
	%br

app/views/shared/_prevblockshowplace.html.erb
<div class='shpage'>
<div class='prevsh'>
<%= link_to_prev @showplaces, {:param_name => :shpage, :remote => true}, (image_tag '/img/content_arr_slider_left.png') %>
</a></div>
<div class='contsh'>

app/views/shared/_signin.html.haml
.modal.fade{:id=>"sign_in", :tabindex=>"-1", :role=>"dialog", 'aria-labelledby'=>"signinLabel", 'aria-hidden'=>"true", :style=>'display:none'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{:type=>"button", 'data-dismiss'=>"modal", 'aria-hidden'=>"true"} &times; 
        %h4{:class=>'modal-title', :id=>"signinLabel"} 
          = t('user.signblock')
      %div{:class=>'modal-body'}
        
        = form_for(User.new, url: session_path(:user), html:{id: 'sign_in_user', :'data-type' => 'json'}, remote: true) do |f|
          .form-inputs
            .form-group
              = f.label :login, t('user.username'), class: "control-label"
              .inpt
                = f.text_field :login, autofocus: true, required: true, class: "form-control", style: "width:180px;float:left;margin-right: 10px;"
                %p{style: "padding-top: 6px;"} 
                  = link_to "Регистрация", new_registration_path(:user)
            .form-group
              = f.label :password, t('user.password'), class: "control-label"
              .inpt
                = f.password_field :password, autocomplete: "off", class: "form-control", style: "width:180px;float:left;margin-right: 10px;"
                %p{style: "padding-top: 6px;"}
                  = link_to "Забыли пароль?", new_password_path(:user)
            .form-inline
              = f.check_box :remember_me
              = f.label :remember_me, t('user.remember')
          .modalfooter
            .form-group{align: "center"}
              = f.submit t('user.sign'), class: "btn btn-primary"
      .modal-footer