config/routes.rb
Allworld::Application.routes.draw do
  post 'ajax/showhide'

  mount Ckeditor::Engine => '/ckeditor'
  get "persons/profile"
  get 'persons/profile', as: 'user_root'
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get '/place/:tag', to: 'home#place'
  get '/country/:tag', to: 'home#country'
  get '/allnews', to: 'home#allnews'
  post '/allnews_filter', to: 'home#allnews_filter'
  post '/allnews_showmore', to: 'home#allnews_showmore'
  post '/allnews_showmore_events', to: 'home#allnews_showmore_events'
  post '/allnews_showmore_news', to: 'home#allnews_showmore_news'
  post '/all_country_news_showmore', to: 'home#all_country_news_showmore'
  post '/next_news', to: 'home#next_news'
  post '/prev_news', to: 'home#prev_news'
  get '/news/:tag', to: 'home#news'
  get '/countries/:tag', to: 'home#countries'
  get '/section/:tag', to: 'home#section'
  get '/categories/:tag', to: 'home#categories'
  get '/allbest', to: 'home#allbest'
  get '/allwonders', to: 'home#allwonders'
  get '/allcountries', to: 'home#allcountries'
  get '/goroda', to: 'home#goroda'
  get '/search', to: 'application#search'

  get '/seen/:id', to: 'home#seen'
  get '/multyseen/:id/:country', to: 'home#multyseen'
  post '/multiseen/:id', to: 'placevidels#multiseen', as: :placevidels_multiseen
  get '/seenjs/:id', to: 'ajax#seenjs'
  get '/wishjs/:id', to: 'ajax#wishjs'
  get '/w', to: 'ajax#setsize'
  get '/wish/:id', to: 'home#wish'
  post '/multiwish/:id', to: 'placevidels#multiwish', as: :placevidels_multiwish
  get '/no/:id', to: 'home#no'

  get '/noseen/:id', to: 'home#noseen'
  get '/nowish/:id', to: 'home#nowish'
  get '/nono/:id', to: 'home#nono'

  get '/clickandgo/:id', to: 'home#clickandgo'

  get '/articles/:tag', to: 'home#submenu'
  get '/article/:tag', to: 'home#page'

  get "guide", to: 'home#index', :as =>'guide'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  
  get '/users/profile' => 'users#edit', as: :profile
  match '/users/update_profile' => 'users#update', via: [:put, :patch], as: :update_profile

  get '/api/search' => 'application#api_search', as: :api_search

  root :to => 'home#index'

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :descrip, :hint, :name, :sortorder, :googlemap
  has_one :tag, :as => :content
  has_many :countries
  has_many :showplaces
  after_create :add_tag
  
  def add_tag
    self.tag = Tag.new
    tag  = self.name.to_slug_param
    i    = 1
    ttag = tag
    while Tag.find_by_name(ttag).present? 
      ttag  = tag + '_' + i.to_s
      i = i + 1
    end
    self.tag.name = ttag
    self.tag.save
  end
  rails_admin do
    navigation_label I18n.t('menu.menu')
    list do
      sort_by :sortorder
      field :sortorder
      field :name
      field :tag
    end
    edit do
      include_all_fields
      field :descrip, :ck_editor
      field :hint, :ck_editor
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!, :except => [:place, :index, :country, :allbest, :allwonders, :allcountries, :categories, :section, :countries, :clickandgo ]
  respond_to :html, :json

  def glavnaya
    #render :layout => 'lending'
  end


  def index
    countobj = $countobj
    @perpaged = $perpaged
    @placevidels = nil
    @placedas = nil
    @placenets = nil
    usedplace = []
    if current_user
      unless session[:placevidels].nil?
        session[:placevidels].each do |sesplacevidel|
          unless test = current_user.placevidels.where('showplace_id'=>sesplacevidel).first
            placevidel = Placevidel.new
            placevidel.user = current_user
            placevidel.showplace_id=sesplacevidel
            placevidel.countryarray = Showplace.find(sesplacevidel).countries.first.id.to_s
            fullcountryarray = ''
            comma = ''
            Showplace.find(sesplacevidel).countries.order('id ASC').each do |counryid|
              fullcountryarray = fullcountryarray + comma + counryid.id.to_s
              comma = ','
            end
            placevidel.fullcountryarray = fullcountryarray

            placevidel.save
            current_user.placenets.where('showplace_id'=>sesplacevidel).delete_all
          end
        end
        session.delete(:placevidels)
      end
      unless session[:placedas].nil?
        session[:placedas].each do |sesplaceda|
          unless test = current_user.placedas.where('showplace_id'=>sesplaceda).first
            placeda = Placeda.new
            placeda.user = current_user
            placeda.showplace_id=sesplaceda
            placeda.save
            current_user.placenets.where('showplace_id'=>sesplaceda).delete_all
          end
        end
        session.delete(:placedas)
      end
      unless session[:placenets].nil?
        session[:placenets].each do |sesplacenet|
          unless test = current_user.placenets.where('showplace_id'=>sesplacenet).first
            placenet = Placenet.new
            placenet.user = current_user
            placenet.showplace_id=sesplacenet
            placenet.save
            current_user.placedas.where('showplace_id'=>sesplacenet).delete_all
            current_user.placevidels.where('showplace_id'=>sesplacenet).delete_all
          end
        end
        session.delete(:placenets)
      end
      unless current_user.placevidels.first.nil?
        videlplace = current_user.placevidels.select('placevidels.showplace_id as id').to_a
        #nomultvidelplace = current_user.placevidels.select('placevidels.showplace_id as id').where('countryarray = fullcountryarray').to_a
        @placevidels  = Showplace.where(:id => videlplace).page(params[:vidpage]).per(@perpaged)
        @placevidelscount = Showplace.where(:id => videlplace).count
        countobj = countobj -@perpaged
        usedplace << videlplace
      end
      unless current_user.placedas.first.nil?
        daplace = current_user.placedas.select('placedas.showplace_id as id').to_a
        @placedas  = Showplace.where(:id => daplace).page(params[:dapage]).per(@perpaged)
        @placedascount = Showplace.where(:id => daplace).count
        countobj = countobj -@perpaged
        usedplace << daplace
      end
      unless current_user.placenets.first.nil?
        netplace = current_user.placenets.select('placenets.showplace_id as id').to_a
        @placenets  = Showplace.where(:id => netplace).page(params[:netpage]).per(@perpaged)
        @placenetscount = Showplace.where(:id => netplace).count
        countobj = countobj -@perpaged
        usedplace << netplace
      end
      #unless session[:placedas].blank? ->save to base
    else
      unless session[:placevidels].blank?
        @placevidels  = Showplace.where(:id => session[:placevidels]).page(params[:vidpage]).per(@perpaged)
        @placevidelscount = Showplace.where(:id => session[:placevidels]).count
        countobj = countobj -@perpaged
        usedplace << session[:placevidels]
      end
      unless session[:placedas].blank?
        @placedas     = Showplace.where(:id => session[:placedas]).page(params[:dapage]).per(@perpaged)
        @placedascount = Showplace.where(:id => session[:placedas]).count
        countobj = countobj -@perpaged
        usedplace << session[:placedas]
      end
      unless session[:placenets].blank?
        @placenets    = Showplace.where(:id => session[:placenets]).page(params[:netpage]).per(@perpaged)
        @placenetscount = Showplace.where(:id => session[:placenets]).count
        countobj = countobj -@perpaged
        usedplace << session[:placenets]
      end
    end
    @showplaces = Showplace.for_user(current_user).where(:showhome =>true).where.not(:id =>usedplace).order("RAND(id)").page(params[:shpage]).per(countobj)
  end

  def place
    @showplace = Showplace.for_user(current_user).find_by_tag!(params[:tag])
    #@relatedspls = @showplace.countries.first.showplaces.where.not(:id => @showplace.id).page(params[:page]).per($perpaged)
    #@relatedsplscount = @showplace.countries.first.showplaces.where.not(:id => @showplace.id).count

    render :layout => 'fixed'
  end

  def page
    @page = Staticpage.find_by_tag(params[:tag])
  end

  def submenu
    @submenu = Menulast.find_by_tag(params[:tag])
  end

  def country
    @country = Country.find_by_tag(params[:tag])
    @relatedspls = @country.showplaces.for_user(current_user).where('showincountry = 1').order('point DESC').page(params[:page]).per($perpaged*3)
    @relatedsplscount = @country.showplaces.for_user(current_user).where('showincountry = 1').count
    render :layout => 'fixed'
  end

  def allbest
    @showplaces = Showplace.for_user(current_user).where('top100 = 1').page(params[:shpage]).per(20)
    @showplacescount = Showplace.for_user(current_user).where('top100 = 1').count
  end

  def allwonders
    @showplaces = Showplace.for_user(current_user).where('wonders7 = 1').page(params[:shpage]).per(20)
    @showplacescount = Showplace.for_user(current_user).where('wonders7 = 1').count
  end

  def allcountries
    render :layout => 'fixed'
  end

  def categories
    @category = Tag.find_by_name(params[:tag]).content
    @showplaces = @category.showplaces.for_user(current_user).where('showinsection = 1').page(params[:shpage]).per(20)
    @showplacescount = @category.showplaces.for_user(current_user).where('showinsection = 1').count
  end

  def section
    @section = Tag.find_by_name(params[:tag]).content
    @showplaces = @section.showplaces.for_user(current_user).where('showinsection = 1').page(params[:shpage]).per(20)
    @showplacescount = @section.showplaces.for_user(current_user).where('showinsection = 1').count
  end

  def goroda
    @showplaces = Showplace.for_user(current_user).where('itsgorod = 1').page(params[:shpage]).per(20)
    @showplacescount = Showplace.for_user(current_user).where('itsgorod = 1').count
  end


  def countries
    @region = Tag.find_by_name(params[:tag]).content
    @countries = @region.countries
    render :layout => 'fixed'
  end


  def seen
    if current_user
      if @test = current_user.placevidels.where('showplace_id'=>params[:id]).first
        flash[:danger] = "Exist"
        redirect_to :back
      else
        current_user.placenets.where('showplace_id'=>params[:id]).delete_all
        @placevidel = Placevidel.new
        @placevidel.user = current_user
        @placevidel.showplace_id=params[:id]
        @placevidel.countryarray = Showplace.find(params[:id]).countries.first.id.to_s
        fullcountryarray = ''
        comma = ''
        Showplace.find(params[:id]).countries.order('id ASC').each do |counryid|
          fullcountryarray = fullcountryarray + comma + counryid.id.to_s
          comma=','
        end
        @placevidel.fullcountryarray = fullcountryarray
        if @placevidel.save
          redirect_to :back
        else
          redirect_to :back
        end
      end
    else
      session[:placevidels] =[] if session[:placevidels].nil?
      session[:placenets] =[] if session[:placenets].nil?
      unless session[:placevidels].include?(params[:id])
         session[:placevidels] << params[:id]
         session[:placenets].delete(params[:id])
      end
      session[:placevidelscountries] = [] if session[:placevidelscountries].nil?
      session[:placevidelscountries][params[:id].to_i] = [] if session[:placevidelscountries][params[:id].to_i].nil?
      session[:placevidelscountries][params[:id].to_i] = [Showplace.find(params[:id]).countries.first.id]
      redirect_to :back
    end
  end

  def multyseen
    if current_user
      # shplece - Placevid object
      if shplece = current_user.placevidels.where('showplace_id'=>params[:id]).first

        # Full countries array of Placevid object in which user seen this object
        shplccntarr = shplece.countryarray.split(",").map { |s| s.to_i }

        # if country array already contain selected country - delete from list
        if shplccntarr.include?(params[:country].to_i)
          shplccntarr.delete(params[:country].to_i)
        # else - add new country to array
        else
          shplccntarr << params[:country].to_i
        end


        # TODO: refactor this with join()
        fullcountryarray = ''
        comma = ''
        shplccntarr.uniq.sort.each do |counryid|
          fullcountryarray = fullcountryarray + comma + counryid.to_s
          comma=','
        end

        # TODO: refactor this with 1-line
        shplece.countryarray = fullcountryarray
        shplece.save

        # if country array is blank - delete record
        if shplccntarr.blank?
          current_user.placevidels.where('showplace_id'=>params[:id]).delete_all
        end

        redirect_to :back
      else
        current_user.placenets.where('showplace_id'=>params[:id]).delete_all
        @placevidel = Placevidel.new
        @placevidel.user = current_user
        @placevidel.showplace_id=params[:id]

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_allnews_news_tab.html.haml
- @news_news.reverse.each do |newsblock|
  .col-md-3
    %b
    .textblock.all-news-block.gray-shadow{onclick: "window.location = '/news/"+newsblock.tag+"'"}
      .microblock
        .showplace_wcorner
          .showplace_img
            - if tmpimage = newsblock.newspictures.first
              = image_tag tmpimage.image.url(:thumb)
      .all-news-text
        %span.news-date
          = newsblock.posted_on.try(:strftime, ("%d.%m.%Y"))
        = link_to newsblock.name, "/news/"+newsblock.tag
        .clear
%p
  .col-md-12
    - if @news_news.count != @allnews_news.count
      = form_tag allnews_showmore_news_path, remote: true do
        = hidden_field_tag :page, @page
        - if @country_ids.present?
          - @country_ids.each do |ci|
            = hidden_field_tag "country_ids[]", ci

        = submit_tag "ПОКАЗАТЬ ЕЩЕ", class: "showmore-button"
      = link_to "", "#countries_ids", class: "goup-button"
    - else
      = link_to "", "#countries_ids", class: "goup-button showmoreless"

app/views/home/_allwonders.html.haml
.page-header
  %h1 Чудеса света
- Chudesa.all.order('sortorder ASC').each do |chudesa|
  .showplace_block.nonaklonniytext
    %h4
      %b=chudesa.name
    %span= raw chudesa.toptext
    .shpage_null
      -#.prevsh
        =image_tag '/img/content_arr_slider_left.png'
      .contsh
        - chudesa.showplaces.for_user(current_user).each do |showplace|
          = render :partial => 'shared/showplace', :locals => {:showplace => showplace}
      -#.nextsh
        =image_tag '/img/content_arr_slider_right.png'
    %span= raw chudesa.bottomtext
  %br
  %br

app/views/home/_news_neighbours.html.haml
.row
  - piece = @neighbours[:prev]
  .col-md-1
    - if piece
      = form_tag prev_news_path, remote: true do
        = hidden_field_tag :id, piece.try(:id)
        = hidden_field_tag :current_id, @current_news_id

        = submit_tag "", class: "left-arrow-button"
  .col-md-4.older-news.neighbour
    - if piece
      .inherit-height
        %b
          = link_to piece.name, "/news/"+piece.tag
        %span.news-date
          = piece.posted_on.try(:strftime, ("%d.%m.%Y"))
        %p
        .tcell(style="width:40%;")
          - if tmpimage = piece.newspictures.first
            .showplace_wcorner_40
              .showplace_img
                = image_tag tmpimage.image.url(:thumb)
        .tcell
          .older-news-text
            = piece.page.html_safe
  .col-md-1.text-center
    #vertical-separator
  - piece = @neighbours[:next]
  .col-md-4.older-news.neighbour
    - if piece
      .inherit-height
        %b
          = link_to piece.name, "/news/"+piece.tag
        %span.news-date
          = piece.posted_on.try(:strftime, ("%d.%m.%Y"))
        %p
        .tcell(style="width:40%;")
          - if tmpimage = piece.newspictures.first
            .showplace_wcorner_40
              .showplace_img
                = image_tag tmpimage.image.url(:thumb)
        .tcell
          .older-news-text
            = piece.page.html_safe
  .col-md-1
    - if piece
      = form_tag next_news_path, remote: true do
        = hidden_field_tag :id, piece.try(:id)
        = hidden_field_tag :current_id, @current_news_id

        = submit_tag "", class: "right-arrow-button"

app/views/home/all_country_news_showmore.js.erb
$(function() {

  $("#all_country_news .textsblocks").html("<%= j render 'country_news_tab'%>");
  
  $(".country-select").change(function(){
    $(this).parent().submit();
  });

  $(".tabmenu:not(.constant) .tabmenu-header .tab-link").click(function(){
    $(".tabmenu:not(.constant) .tab-panel").removeClass("active");
    $(".tabmenu:not(.constant) .tab-panel[id='"+$(this).children("span").attr("tab-id")+"']").addClass("active");

    $(".tabmenu:not(.constant) .tabmenu-header .tab-link").removeClass("active");
    $(this).addClass("active");
  });

});

app/views/home/allnews.html.haml
- set_meta_tags title: "Новости", reverse: true

- @bredcrumb = capture do
  %li= link_to 'Путеводитель', '/'
  %li.active Новости
/ .page-header
/   %h1{style: "text-align:left;"} Новости

= content_for :precontainer do
  .country-selector-block
    .country-selector-form
      = form_for :countries, url: allnews_filter_path, remote: true do |f|
        = f.label :ids, "Выбрать страну", style: "color: white"
        %nobr
          = f.select :ids, Country.ordered.select{|c| c.news.any?}.map{|c| [c.name,c.id]}, {}, multiple: true, class: "country-select"

= content_for :postcontainer do
  .place-for-news
    = render "shared/allnews_tabmenu"

app/views/home/allnews_filter.js.erb
$(function() {

  $(".place-for-news").html("<%= j render 'shared/allnews_tabmenu' %>");
  
  $(".country-select").change(function(){
    $(this).parent().submit();
  });

  $(".tabmenu:not(.constant) .tabmenu-header .tab-link").click(function(){
    $(".tabmenu:not(.constant) .tab-panel").removeClass("active");
    $(".tabmenu:not(.constant) .tab-panel[id='"+$(this).children("span").attr("tab-id")+"']").addClass("active");

    $(".tabmenu:not(.constant) .tabmenu-header .tab-link").removeClass("active");
    $(this).addClass("active");
  });

});

app/views/home/allnews_showmore.js.erb
$(function() {

  $("#all_news .textsblocks").html("<%= j render 'allnews_all_tab'%>");
  
  $(".country-select").change(function(){
    $(this).parent().submit();
  });

  $(".tabmenu:not(.constant) .tabmenu-header .tab-link").click(function(){
    $(".tabmenu:not(.constant) .tab-panel").removeClass("active");
    $(".tabmenu:not(.constant) .tab-panel[id='"+$(this).children("span").attr("tab-id")+"']").addClass("active");

    $(".tabmenu:not(.constant) .tabmenu-header .tab-link").removeClass("active");
    $(this).addClass("active");
  });

});

app/views/home/categories.js.erb
$('#contenetblock').html('<%= escape_javascript render :partial => "listener", :locals => { :blockname => @category.name } %>');

app/views/home/country.js.erb
$('#related').html('<%= escape_javascript render('relatedspls') %>');

app/views/home/glavnaya.html.haml
-@bredcrumb='<li><a href="/">Главная</a></li>'
%h1
  Это будет интересно и полезно тем, кто:
.rowsection
  - Homekarusel.order('sortorder ASC').first(3).each do |section|
    .pull-left.section
      .blockimgsection
        =image_tag section.image.url(:block)
      .sectiontitle
        =section.name
.clear
.rowsection
  -unless Allsetting.where(:default => true).first.homeinfografik.blank?
    =image_tag Allsetting.where(:default => true).first.homeinfografik.url(:block)
.clear
%h1
  Открой мир незабываемых впечатлений
.rowsection
  - Section.order('sortorder ASC').each do |section|
    .pull-left.section
      = link_to "/section/"+section.tag.name do
        .blockimgsection
          =image_tag section.image.url(:block)
        .sectiontitle
          =section.name
.clear

app/views/home/index.html.haml
- set_meta_tags title: "Путеводитель", description: "AllWorld travel - это информационный сервис для путешественников, предоставляющий детальную информацию о достопримечательностях мира, а также позволяющий забронировать все необходимые сопутствующие услуги", keywords: "туризм, путешествие, лучшие туры, активный отдых, страны мира, лучшие страны мира, сайт туризм, туризм мира, активный туризм"

-@bredcrumb='<li><a href="/">Путеводитель</a></li>'
= render :partial => 'index'

app/views/home/place.js.erb
// $('#textblockscontent').html('<%= escape_javascript render('textblokscontent') %>');
window.location.reload();